======================
100-matrix_mul
======================

Matrix multiplication  module is used to test the matrix_mul function

=====================

Import the function:
    >>> matrix_mul = __import__('100-matrix_mul').matrix_mul

Test cases:
    >>> m_a = [[1, 2], [3, 4],]
    >>> m_b = m_a
    >>> print(matrix_mul(m_a, m_b))
    [[7, 10], [15, 22]]

Test with a second matrix:
    >>> m_a = [[1, 2]]
    >>> m_b = [[3, 4], [5, 6]]
    >>> print(matrix_mul(m_a, m_b))
    [[13, 16]]

Test with float numbers:
    >>> m_a = [[1.5, 2.5, 1.2], [3.6, -3.3, 2.2]]
    >>> m_b = [[1.0, 2.1], [2.9, 2.4], [3.2, -2.4]]
    >>> print(matrix_mul(m_a, m_b))
    [[12.59, 6.2700000000000005], [1.070000000000002, -5.639999999999999]]

Test with both integers and floats:
    >>> m_a = [[1.2, 1.5, 2.2, 2], [4.66, 3, -1.2, 2]]
    >>> m_b = [[1.0, 3.3, 2], [-2.9, 4.4, 1], [2, 3.2, 4.4], [1, 2, 3]]
    >>> print(matrix_mul(m_a, m_b))
    [[3.250000000000001, 21.6, 19.580000000000002], [-4.4399999999999995, 28.738000000000003, 13.04]]

TypeError for empty values in m_a matrix:
    >>> print(matrix_mul([], [[1, 2]]))
    Traceback (most recent call last):
    ValueError: m_a can't be empty

TypeError for empty values in m_b matrix:
    >>> print(matrix_mul([[]], []))
    Traceback (most recent call last):
    ValueError: m_a can't be empty

TypeError for when m_b is not a list:
    >>> print(matrix_mul([], [[]]))
    Traceback (most recent call last):
    ValueError: m_a can't be empty

TypeError for when m_a is not a list:
    >>> print(matrix_mul("string", [[1, 2]]))
    Traceback (most recent call last):
    TypeError: m_a must be a list

TypeError for when m_b is not a list:
    >>> print(matrix_mul([[1, 2]], "string"))
    Traceback (most recent call last):
    TypeError: m_b must be a list

TypeError for when m_a and mat_b are not lists:
    >>> print(matrix_mul("string1", "string2"))
    Traceback (most recent call last):
    TypeError: m_a must be a list

TypeError m_a and m_b are None
    >>> print(matrix_mul(None, None))
    Traceback (most recent call last):
    TypeError: m_a must be a list
